### ISSUE TITLE
Env variable when deploying to heroku

### ISSUE THREAD

**Issue by nihirisuto** [MitchTalmadge/discord-echobot#22]
In Heroku settings there's actually a section for config vars, is this an appropriate place to put the env variable?

Since this is a BASH-style variable, I'm unsure how to key:value the data. Readme says formatting doesn't matter, but there are nested data values. Should I be using an associated array?

Cheers

**Comment by MitchTalmadge** [comment]
Hey! All you have to do is use `ECHOBOT_CONFIG_JSON` as the key and copy-paste the entire contents of config.json as the value. By formatting not mattering I just mean you can disregard line breaks or spaces or tabs. JSON does not care about those. It's just to make it pretty.

**Comment by nihirisuto** [comment]
> Hey! All you have to do is use `ECHOBOT_CONFIG_JSON` as the key and copy-paste the entire contents of config.json as the value. By formatting not mattering I just mean you can disregard line breaks or spaces or tabs.

Thank you for the prompt reply! I went ahead and did that and something about the array brackets `]` is breaking my start. 

```
2021-03-02T20:58:05.294458+00:00 app[web.1]: > node ./bin/echobot.js
2021-03-02T20:58:05.294458+00:00 app[web.1]: 
2021-03-02T20:58:05.830986+00:00 app[web.1]: undefined:7
2021-03-02T20:58:05.831024+00:00 app[web.1]:       ],
2021-03-02T20:58:05.831025+00:00 app[web.1]:       ^
2021-03-02T20:58:05.831025+00:00 app[web.1]: 
2021-03-02T20:58:05.831028+00:00 app[web.1]: SyntaxError: Unexpected token ] in JSON at position 154
2021-03-02T20:58:05.831029+00:00 app[web.1]:     at JSON.parse (<anonymous>)
2021-03-02T20:58:05.831030+00:00 app[web.1]:     at EchoBot.loadConfiguration (/app/bin/echobot.js:39:27)
2021-03-02T20:58:05.831031+00:00 app[web.1]:     at new EchoBot (/app/bin/echobot.js:29:19)
2021-03-02T20:58:05.831031+00:00 app[web.1]:     at Object.<anonymous> (/app/bin/echobot.js:257:1)
2021-03-02T20:58:05.831032+00:00 app[web.1]:     at Module._compile (internal/modules/cjs/loader.js:1158:30)
2021-03-02T20:58:05.831033+00:00 app[web.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
2021-03-02T20:58:05.831034+00:00 app[web.1]:     at Module.load (internal/modules/cjs/loader.js:1002:32)
2021-03-02T20:58:05.831034+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
2021-03-02T20:58:05.831036+00:00 app[web.1]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
2021-03-02T20:58:05.831036+00:00 app[web.1]:     at internal/main/run_main_module.js:18:47
```

Here's what my config looks like that I'm pasting into the `ECHOBOT_CONFIG_JSON` value section: 

```JSON
{
  "token": "redacted token for public github issue comment",
  "redirects": [
    {
      "sources": [
        "redacted source for public github issue comment",
      ],
      "destinations": [
        "redacted destination for public github issue comment",
      ],
      "options": {
        "title": "New Copied Message",
        "richEmbed": true,
        "richEmbedColor": 30975,
        "includeSource": true,
        "removeEveryone": true,
        "removeHere": true,
        "copyRichEmbed": true,
        "copyAttachments": true,
        "minLength": 0,
        "allowList": []
      }
    }
  ]
}
```

---

EDIT: Closing this issue. I had commas after single values in the source/destination ! Woops! Thank you for all the help!
